package protogen

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/emirpasic/gods/sets/treeset"
	"github.com/rogpeppe/go-internal/lockedfile"
	"github.com/tableauio/tableau/internal/printer"
	"github.com/tableauio/tableau/internal/strcase"
	"github.com/tableauio/tableau/internal/types"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/internal/x/xproto"
	"github.com/tableauio/tableau/log"
	"github.com/tableauio/tableau/proto/tableaupb"
	"github.com/tableauio/tableau/proto/tableaupb/internalpb"
	"github.com/tableauio/tableau/xerrors"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type bookExporter struct {
	ProtoPackage     string
	ProtoFileOptions map[string]string
	OutputDir        string
	FilenameSuffix   string
	wb               *internalpb.Workbook

	gen *Generator

	messagerPatternRegexp *regexp.Regexp

	// auxFiles holds auxiliary shard proto files produced by union splitting
	// (see UnionOptions.split_threshold). Empty when no union is split.
	auxFiles []*unionAuxFile
	// auxImportPaths holds the relative paths of aux files that the main proto
	// file needs to `import`. Populated together with auxFiles.
	auxImportPaths []string
}

// unionAuxFile is a shard proto file emitted for a large union, holding a
// slice of extracted top-level sub-messages.
type unionAuxFile struct {
	RelPath string           // relative proto path, e.g. "foo_targets_1.proto"
	Printer *printer.Printer // body: `message ... {...}` for each extracted sub-message
	Imports map[string]bool  // proto imports needed by the shard body
}

func newBookExporter(protoPackage string, protoFileOptions map[string]string, outputDir, filenameSuffix string, wb *internalpb.Workbook, gen *Generator) *bookExporter {
	return &bookExporter{
		ProtoPackage:          protoPackage,
		ProtoFileOptions:      protoFileOptions,
		OutputDir:             outputDir,
		FilenameSuffix:        filenameSuffix,
		wb:                    wb,
		gen:                   gen,
		messagerPatternRegexp: regexp.MustCompile(gen.InputOpt.MessagerPattern),
	}
}

func (x *bookExporter) GetProtoFilePath() string {
	return genProtoFilePath(x.wb.Name, x.FilenameSuffix)
}

func (x *bookExporter) export(checkProtoFileConflicts bool) error {
	// log.Debug(proto.MarshalTextString(wb))
	p1 := printer.New()
	p1.P("// Code generated by tableau (protogen v", Version, "). DO NOT EDIT.")
	p1.P("// clang-format off")
	p1.P("")
	p1.P(`syntax = "proto3";`)
	p1.P("")
	p1.P("package ", x.ProtoPackage, ";")
	p1.P("")

	// keep the elements ordered by import path
	set := treeset.NewWithStringComparator()
	set.Add(tableauProtoPath) // default must be imported path
	p3 := printer.New()
	for i, ws := range x.wb.Worksheets {
		se := &sheetExporter{
			be:             x,
			ws:             ws,
			p:              p3,
			isLastSheet:    i == len(x.wb.Worksheets)-1,
			typeInfos:      x.gen.typeInfos,
			nestedMessages: make(map[string]*internalpb.Field),
			Imports:        make(map[string]bool),
		}
		if err := se.export(); err != nil {
			return xerrors.WrapKV(err, xerrors.KeySheetName, ws.Name)
		}
		for key := range se.Imports {
			set.Add(key)
		}
	}

	// Add aux-file imports (populated by union split, if any). Keeping them
	// in the same set as regular imports preserves the sorted-by-path order.
	for _, auxPath := range x.auxImportPaths {
		set.Add(auxPath)
	}

	// generate imports
	p2 := printer.New()
	for _, key := range set.Values() {
		p2.P(`import "`, key, `";`)
	}
	p2.P("")
	for k, v := range x.ProtoFileOptions {
		p2.P(`option `, k, ` = "`, v, `";`)
	}
	p2.P("option (tableau.workbook) = {", marshalToText(x.wb.Options), "};")
	p2.P("")

	relPath := x.GetProtoFilePath()
	path := filepath.Join(x.OutputDir, relPath)
	log.Infof("%15s: %s", "generated proto", relPath)

	// mu := lockedfile.MutexAt(path)
	// unlock, err := mu.Lock()
	// if err != nil {
	// 	return xerrors.Wrapf(err, "failed to lock file: %s", path)
	// }
	// defer unlock()

	// NOTE: use file lock to protect .proto file from being written concurrently by multiple goroutines
	// refer: https://github.com/golang/go/issues/33974
	// refer: https://go.googlesource.com/proposal/+/master/design/33974-add-public-lockedfile-pkg.md

	if checkProtoFileConflicts {
		if existed, err := xfs.Exists(path); err != nil {
			return xerrors.WrapKV(err)
		} else {
			if existed {
				return xerrors.Newf("file already exists: %s", path)
			}
		}
	}

	if f, err := lockedfile.Create(path); err != nil {
		return xerrors.WrapKV(err)
	} else {
		defer func() {
			err := f.Close()
			if err != nil {
				log.Panicf("failed to close file: %s", path)
			}
		}()
		if _, err = f.Write(p1.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
		if _, err = f.Write(p2.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
		if _, err = f.Write(p3.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
	}

	// Write any auxiliary shard files produced by union splitting.
	for _, aux := range x.auxFiles {
		auxPath := filepath.Join(x.OutputDir, aux.RelPath)
		if err := x.writeAuxFile(aux, auxPath); err != nil {
			return err
		}
		log.Infof("%15s: %s", "generated proto", aux.RelPath)
	}

	return nil
}

// writeAuxFile writes a union split shard proto file. The header (syntax,
// package, imports, file-level options) is generated to match the main proto
// file so protoc can compile the shards independently.
func (x *bookExporter) writeAuxFile(aux *unionAuxFile, path string) error {
	header := printer.New()
	header.P("// Code generated by tableau (protogen v", Version, "). DO NOT EDIT.")
	header.P("// clang-format off")
	header.P("")
	header.P(`syntax = "proto3";`)
	header.P("")
	header.P("package ", x.ProtoPackage, ";")
	header.P("")

	importSet := treeset.NewWithStringComparator()
	for imp := range aux.Imports {
		importSet.Add(imp)
	}
	for _, key := range importSet.Values() {
		header.P(`import "`, key, `";`)
	}
	if importSet.Size() > 0 {
		header.P("")
	}
	for k, v := range x.ProtoFileOptions {
		header.P(`option `, k, ` = "`, v, `";`)
	}
	if len(x.ProtoFileOptions) > 0 {
		header.P("")
	}

	f, err := lockedfile.Create(path)
	if err != nil {
		return xerrors.WrapKV(err)
	}
	defer func() {
		if cerr := f.Close(); cerr != nil {
			log.Panicf("failed to close file: %s", path)
		}
	}()
	if _, err = f.Write(header.Bytes()); err != nil {
		return xerrors.WrapKV(err)
	}
	if _, err = f.Write(aux.Printer.Bytes()); err != nil {
		return xerrors.WrapKV(err)
	}
	return nil
}

type sheetExporter struct {
	be          *bookExporter
	ws          *internalpb.Worksheet
	p           *printer.Printer
	isLastSheet bool
	typeInfos   *xproto.TypeInfos

	Imports        map[string]bool              // import name -> defined
	nestedMessages map[string]*internalpb.Field // top message scoped type name -> field
}

func (x *sheetExporter) export() error {
	mode := x.ws.GetOptions().GetMode()
	switch x.ws.Options.Mode {
	case tableaupb.Mode_MODE_DEFAULT:
		return x.exportMessager()
	case tableaupb.Mode_MODE_ENUM_TYPE, tableaupb.Mode_MODE_ENUM_TYPE_MULTI:
		return x.exportEnum()
	case tableaupb.Mode_MODE_STRUCT_TYPE, tableaupb.Mode_MODE_STRUCT_TYPE_MULTI:
		return x.exportStruct()
	case tableaupb.Mode_MODE_UNION_TYPE, tableaupb.Mode_MODE_UNION_TYPE_MULTI:
		return x.exportUnion()
	default:
		return xerrors.Newf("unknown mode: %v", mode)
	}
}

func (x *sheetExporter) exportEnum() error {
	if x.ws.Note != "" {
		x.p.P("// ", x.ws.Note)
	}
	x.p.P("enum ", x.ws.Name, " {")
	opts := &tableaupb.EnumOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}
	x.p.P("  option (tableau.etype) = {", marshalToText(opts), "};")
	x.p.P("")
	// generate the enum value fields
	for i, field := range x.ws.Fields {
		if i == 0 && field.Number != 0 {
			ename := strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(x.ws.Name) + "_INVALID"
			x.p.P("  ", ename, " = 0;")
		}
		if field.Number == 0 && i != 0 {
			return xerrors.Newf("zero enum value must be the first one, but found at enum value row: %d", i+1)
		}
		note := ""
		if field.Alias != "" {
			note = " // " + field.Alias
		}
		x.p.P("  ", strings.TrimSpace(field.Name), " = ", field.Number, ` [(tableau.evalue).name = "`, strings.TrimSpace(field.Alias), `"];`, note)
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) exportStruct() error {
	x.p.P("message ", x.ws.Name, " {")
	opts := &tableaupb.StructOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}
	x.p.P("  option (tableau.struct) = {", marshalToText(opts), "};")
	x.p.P("")
	// generate the fields
	depth := 1
	for i, field := range x.ws.Fields {
		tagid := i + 1
		if err := x.exportField(depth, tagid, field, x.ws.Name); err != nil {
			return err
		}
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

// unionSplitTypeSep is the separator between the parent union name and the
// extracted sub-message name when a union is split into shard files.
//
// It MUST NOT be "_": protoc-gen-go names each oneof wrapper as
// `<Parent>_<CamelField>`, e.g. oneof field `pvp_battle` under `TaskTarget`
// becomes Go type `TaskTarget_PvpBattle`. If we also named the extracted
// sub-message `TaskTarget_PvpBattle` (i.e. separator="_"), the two Go types
// would collide across files because protoc-gen-go's name disambiguation
// only inspects the current .proto file, producing a `redeclared` compile
// error. Using "T_" gives `TaskTargetT_PvpBattle` for the extracted message,
// which cannot collide with any oneof wrapper name.
//
// Business code typically depends only on the union's Type enum and the
// generated field accessors (both unchanged by splitting), so this rename
// of extracted sub-message types is invisible to callers.
const unionSplitTypeSep = "T_"

// defaultUnionSplitShardSize is the default number of extracted sub-messages
// placed in each shard file when UnionOptions.split_shard_size is not set.
const defaultUnionSplitShardSize = 40

// unionSubMsg describes an extracted sub-message of a split union.
type unionSubMsg struct {
	field *internalpb.Field
	typ   string // sub-message type name (without parent prefix)
}

func (x *sheetExporter) exportUnion() error {
	opts := &tableaupb.UnionOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}

	// Collect sub-messages that carry a message body (candidates for splitting).
	var subMsgs []unionSubMsg
	for _, msgField := range x.ws.Fields {
		if len(msgField.Fields) == 0 {
			continue
		}
		typ := msgField.Name
		if msgField.Type != "" {
			typ = msgField.Type
		}
		subMsgs = append(subMsgs, unionSubMsg{field: msgField, typ: typ})
	}

	// Split only when explicitly enabled (threshold > 0) AND exceeded.
	// InputOpt may be nil in some test scenarios; treat that as disabled.
	threshold := 0
	if x.be.gen.InputOpt != nil {
		threshold = int(x.be.gen.InputOpt.UnionSplitThreshold)
	}
	shouldSplit := threshold > 0 && len(subMsgs) > threshold

	x.p.P("message ", x.ws.Name, " {")
	x.p.P("  option (tableau.union) = {", marshalToText(opts), "};")
	x.p.P()

	typeOpts := &tableaupb.FieldOptions{Name: "Type"}
	x.p.P("  Type type = 9999 [(tableau.field) = {", marshalToText(typeOpts), "}];")
	x.p.P(`  oneof value {`)

	oneOfOpts := &tableaupb.OneofOptions{Note: x.ws.Note, Field: "Field"}
	x.p.P("    option (tableau.oneof) = {", marshalToText(oneOfOpts), "};")
	x.p.P()

	for _, field := range x.ws.Fields {
		ename := "TYPE_" + strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(field.Name)
		typ := field.Name
		if field.FullType != "" {
			typ = field.FullType
		}
		if len(field.Fields) == 0 && field.Type == "" {
			x.p.P("    // No field bound to enum value: ", ename, ".")
			continue
		}
		// When splitting, the oneof references the extracted top-level type
		// name (with unionSplitTypeSep between parent and sub-type). Otherwise
		// keep the original nested name so single-file unions are unchanged.
		if shouldSplit && len(field.Fields) > 0 {
			typ = x.ws.Name + unionSplitTypeSep + typ
		}
		x.p.P("    ", typ, " ", strcase.FromContext(x.be.gen.ctx).ToSnake(field.Name), " = ", field.Number, `; // Bound to enum value: `, ename, ".")
	}
	x.p.P(`  }`)
	x.p.P()

	// generate enum type
	x.p.P("  enum Type {")
	x.p.P("    TYPE_INVALID = 0;")
	for _, field := range x.ws.Fields {
		ename := "TYPE_" + strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(field.Name)
		note := ""
		if field.Alias != "" {
			note = " // " + field.Alias
		}
		x.p.P("    ", ename, " = ", field.Number, ` [(tableau.evalue).name = "`, field.Alias, `"];`, note)
	}
	x.p.P("  }")

	if shouldSplit {
		// Extract sub-messages into shard files as top-level messages. The
		// parent union body remains, but no `message ... { ... }` block is
		// emitted inside it for the extracted sub-messages, so the enum
		// block above is the last content within the union body.
		if err := x.exportUnionSplit(subMsgs); err != nil {
			return err
		}
	} else {
		// Blank line separates the enum block from the nested sub-message
		// definitions that follow (original behavior).
		x.p.P()
		// generate nested sub-message types (original behavior)
		for _, sm := range subMsgs {
			x.p.P("  message ", sm.typ, " {")
			depth := 2
			tagid := 1
			for _, field := range sm.field.Fields {
				if err := x.exportField(depth, tagid, field, sm.field.Name); err != nil {
					return err
				}
				cross := int(field.GetOptions().GetProp().GetCross())
				if cross < 1 {
					cross = 1
				}
				tagid += cross
			}
			x.p.P("  }")
		}
	}

	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

// exportUnionSplit emits the given sub-messages into one or more shard proto
// files as top-level messages named `<Union><Sep><SubType>`. Each shard is
// registered on the parent bookExporter for later writing, and its relative
// path is added to the main file's imports so protoc resolves the type.
func (x *sheetExporter) exportUnionSplit(subMsgs []unionSubMsg) error {
	shardSize := 0
	if x.be.gen.InputOpt != nil {
		shardSize = int(x.be.gen.InputOpt.UnionSplitShardSize)
	}
	if shardSize <= 0 {
		shardSize = defaultUnionSplitShardSize
	}
	numShards := (len(subMsgs) + shardSize - 1) / shardSize

	// Base name for shard files: strip the trailing FilenameSuffix from the
	// main proto path so shards inherit the same suffix convention.
	mainPath := x.be.GetProtoFilePath()
	baseName := strings.TrimSuffix(mainPath, x.be.FilenameSuffix+".proto")
	shardTag := strcase.FromContext(x.be.gen.ctx).ToSnake(x.ws.Name)

	for shardIdx := 0; shardIdx < numShards; shardIdx++ {
		start := shardIdx * shardSize
		end := start + shardSize
		if end > len(subMsgs) {
			end = len(subMsgs)
		}
		shardMsgs := subMsgs[start:end]

		shardRelPath := fmt.Sprintf("%s_%s_%d%s.proto",
			baseName, shardTag, shardIdx+1, x.be.FilenameSuffix)
		shardPrinter := printer.New()
		shardImports := map[string]bool{tableauProtoPath: true}

		for i, sm := range shardMsgs {
			prefixedTyp := x.ws.Name + unionSplitTypeSep + sm.typ
			shardPrinter.P("message ", prefixedTyp, " {")
			// Use a temporary sheetExporter so the extracted sub-message
			// writes into shardPrinter while transitive imports (predefined
			// types, well-known types) are collected locally rather than into
			// the main file's import set.
			tempSe := &sheetExporter{
				be:             x.be,
				ws:             x.ws,
				p:              shardPrinter,
				isLastSheet:    true,
				typeInfos:      x.typeInfos,
				nestedMessages: make(map[string]*internalpb.Field),
				Imports:        make(map[string]bool),
			}
			depth := 1
			tagid := 1
			for _, field := range sm.field.Fields {
				if err := tempSe.exportField(depth, tagid, field, sm.field.Name); err != nil {
					return err
				}
				cross := int(field.GetOptions().GetProp().GetCross())
				if cross < 1 {
					cross = 1
				}
				tagid += cross
			}
			shardPrinter.P("}")
			if i < len(shardMsgs)-1 {
				shardPrinter.P("")
			}
			for imp := range tempSe.Imports {
				shardImports[imp] = true
			}
		}

		x.be.auxFiles = append(x.be.auxFiles, &unionAuxFile{
			RelPath: shardRelPath,
			Printer: shardPrinter,
			Imports: shardImports,
		})
		x.be.auxImportPaths = append(x.be.auxImportPaths, shardRelPath)
	}
	return nil
}

func (x *sheetExporter) exportMessager() error {
	// log.Debugf("workbook: %s", x.ws.String())
	if x.be.messagerPatternRegexp != nil && !x.be.messagerPatternRegexp.MatchString(x.ws.Name) {
		return xerrors.Newf("messager %s does not match pattern %q", x.ws.Name, x.be.messagerPatternRegexp.String())
	}
	x.p.P("message ", x.ws.Name, " {")
	x.p.P("  option (tableau.worksheet) = {", marshalToText(x.ws.Options), "};")
	x.p.P("")
	// generate the fields
	depth := 1
	for i, field := range x.ws.Fields {
		tagid := i + 1
		if err := x.exportField(depth, tagid, field, x.ws.Name); err != nil {
			return err
		}
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) exportField(depth int, tagid int, field *internalpb.Field, prefix string) error {
	label := ""
	if x.ws.GetOptions().GetFieldPresence() &&
		types.IsScalarType(field.FullType) &&
		!types.IsWellKnownMessage(field.FullType) {
		label = "optional "
	}
	note := ""
	if field.Note != "" {
		note = " // " + field.Note
	}
	x.p.P(printer.Indent(depth), label, field.FullType, " ", field.Name, " = ", tagid, " ", genFieldOptionsString(field.Options), ";", note)

	typeName := field.Type
	fullTypeName := field.FullType
	if field.ListEntry != nil {
		typeName = field.ListEntry.ElemType
		fullTypeName = field.ListEntry.ElemFullType
	}
	if field.MapEntry != nil {
		typeName = field.MapEntry.ValueType
		fullTypeName = field.MapEntry.ValueFullType
	}

	if types.IsWellKnownMessage(fullTypeName) {
		importPath := types.GetWellKnownMessageImport(fullTypeName)
		x.Imports[importPath] = true
	}

	if field.Predefined {
		// import the predefined type's parent filename.
		// NOTE: excludes self.
		if typeInfo := x.typeInfos.GetByFullName(protoreflect.FullName(fullTypeName)); typeInfo != nil &&
			typeInfo.ParentFilename != x.be.GetProtoFilePath() {
			x.Imports[typeInfo.ParentFilename] = true
		}
	} else {
		nestedMsgName := prefix + "." + typeName
		switch {
		case field.Fields != nil:
			// iff field is a map or list and message type is not imported.
			if isSameFieldMessageType(field, x.nestedMessages[nestedMsgName]) {
				// if the nested message is the same as the previous one,
				// just use the previous one, and don't generate a new one.
				return nil
			}
		case !types.IsScalarType(typeName):
			if _, ok := x.nestedMessages[nestedMsgName]; ok {
				// if the nested message has the same name with the previous one,
				// just use the previous one, and don't generate a new one.
				return nil
			}
		default:
			return nil
		}
		// bookkeeping this nested msessage, so we can check if we can reuse it later.
		x.nestedMessages[nestedMsgName] = field

		// x.g.P("")
		x.p.P(printer.Indent(depth), "message ", typeName, " {")
		for i, f := range field.Fields {
			tagid := i + 1
			if err := x.exportField(depth+1, tagid, f, nestedMsgName); err != nil {
				return err
			}
		}
		x.p.P(printer.Indent(depth), "}")
	}
	return nil
}

func genFieldOptionsString(opts *tableaupb.FieldOptions) string {
	jsonName := ""
	// remember and then clear protobuf built-in options
	if opts.Prop != nil {
		jsonName = opts.Prop.JsonName
		opts.Prop.JsonName = ""

		// set nil if field prop is empty
		if IsEmptyFieldProp(opts.Prop) {
			opts.Prop = nil
		}
	}

	// compose this field options
	fieldOpts := "[(tableau.field) = {" + marshalToText(opts) + "}"
	if jsonName != "" {
		fieldOpts += `, json_name="` + jsonName + `"`
	}
	fieldOpts += "]"
	return fieldOpts
}

func marshalToText(m protoreflect.ProtoMessage) string {
	// text := proto.CompactTextString(field.Options)
	bin, err := prototext.Marshal(m)
	if err != nil {
		panic(err)
	}
	// NOTE: remove redundant spaces/whitespace from a string
	// refer: https://stackoverflow.com/questions/37290693/how-to-remove-redundant-spaces-whitespace-from-a-string-in-golang
	text := strings.Join(strings.Fields(string(bin)), " ")
	return text
}

func isSameFieldMessageType(left, right *internalpb.Field) bool {
	if left.GetType() == right.GetType() &&
		left.GetFullType() == right.GetFullType() &&
		len(left.GetFields()) == len(right.GetFields()) {
		for i, l := range left.GetFields() {
			r := right.GetFields()[i]
			if !isSameFieldMessageType(l, r) {
				return false
			}
		}
		return true
	}
	return false
}
